export function ownerLabsResponse(): Response {
  const html = String.raw`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>SakuraPanel Labs</title>
<style>
:root{color-scheme:dark}body{font-family:-apple-system,BlinkMacSystemFont,sans-serif;max-width:900px;margin:0 auto;padding:18px;background:#101010;color:#f8f8f8}
a{color:#f08dbd}.muted{color:#aaa}.card{background:#191919;border:1px solid #303030;border-radius:16px;padding:16px;margin:12px 0}
button,input,select{box-sizing:border-box;padding:11px;margin:5px 0;border-radius:9px;border:1px solid #444;background:#222;color:#fff}
button{background:#d85f9d;border:0;font-weight:700}pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:360px;overflow:auto}.row{display:flex;gap:8px;flex-wrap:wrap}.row>*{flex:1;min-width:130px}.status{font-weight:700}.good{color:#83e6a1}.bad{color:#ff9b9b}.warn{color:#f4d38a}.config-item{display:block;padding:9px;margin:5px 0;border:1px solid #333;border-radius:8px}.config-item input{margin-right:10px}
</style></head><body>
<p><a href="/owner">← Owner dashboard</a></p><h1>🌸 SakuraPanel v1 Systems</h1>
<p class="muted">Private operational tools. Every API call is authorized server-side; diagnostic output does not include secrets.</p>
<section class="card"><h2>Config Studio</h2>
<div class="row"><input id="userId" placeholder="Target user ID (optional)"><input id="subscriptionId" placeholder="Subscription ID (for subscription export)"><select id="format"><option value="json">Validated JSON</option><option value="links">Existing protocol links</option><option value="subscription">Subscription JSON (requires subscription ID)</option></select><button id="export">Generate export</button></div>
<div class="row"><button id="refreshConfigs">Load / refresh configurations</button><select id="configFilter"><option value="all">All states</option><option value="active">Active / eligible</option><option value="expired">Expired</option><option value="disabled">Disabled / suspended</option><option value="invalid">Invalid</option><option value="sensitive">Contains sensitive fields</option></select><button id="selectVisible">Select visible</button><button id="clearSelection">Clear selection</button></div><p id="configListStatus" class="muted">Configuration list not loaded.</p><div id="configList"></div><p id="exportStatus" class="muted">No export generated.</p><button id="download" hidden>Download export</button><pre id="exportBody"></pre></section>
<section class="card"><h2>Sakura Pulse</h2><p class="muted">Read-only D1/schema, foreign-key, and Emergency Lock binding checks.</p><button id="pulse">Run health checks</button><pre id="pulseResult">Not run.</pre></section>
<section class="card"><h2>Sakura Speed Lab</h2><p class="muted">One bounded server-side database query and local JSON serialization sample. Not a benchmark.</p><button id="speed">Measure sample</button><pre id="speedResult">Not run.</pre></section>
<section class="card"><h2>Route Advisor</h2><p class="muted">Advisory only. The current schema removed the legacy endpoint model, so this remains insufficient-data until supported route candidates exist.</p><button id="routes">Check recommendation status</button><pre id="routeResult">Not run.</pre></section>
<script>
const $=id=>document.getElementById(id);let lastExport=null;let configItems=[];let selectedIds=new Set();
async function api(path,options={}){const r=await fetch(path,{credentials:"same-origin",...options,headers:{"content-type":"application/json",...(options.headers||{})}});let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error((j&&j.error)||("HTTP "+r.status));return j}
function show(id,value){$(id).textContent=JSON.stringify(value,null,2)}
function renderConfigItems(){const filter=$("configFilter").value;const visible=configItems.filter(item=>filter==="all"||item.state===filter);const root=$("configList");root.replaceChildren();for(const item of visible){const label=document.createElement("label");label.className="config-item";const input=document.createElement("input");input.type="checkbox";input.className="config-choice";input.value=item.id;input.checked=selectedIds.has(item.id);input.onchange=()=>{if(input.checked)selectedIds.add(item.id);else selectedIds.delete(item.id);};const details=document.createElement("span");details.textContent=item.id+" · "+item.templateId+" · "+item.state+(item.reasons.length?" · "+item.reasons.join(", "):"");label.append(input,details);root.append(label)}$("configListStatus").textContent=visible.length+" shown · "+configItems.length+" loaded · "+selectedIds.size+" selected"+(configItems.length>=100?" (display limit 100)":"");}
async function loadConfigs(){const status=$("configListStatus");selectedIds.clear();status.textContent="Loading configuration metadata…";try{const q=new URLSearchParams({format:"inspect"});if($("userId").value.trim())q.set("userId",$("userId").value.trim());const r=await api("/internal/config-studio?"+q.toString());configItems=r.value.items||[];renderConfigItems();if(r.value.truncated)status.textContent+=" · More records exist; list is capped at 100."; }catch(e){configItems=[];renderConfigItems();status.textContent="Unable to load configurations: "+String(e)}}
$("refreshConfigs").onclick=loadConfigs;$("configFilter").onchange=renderConfigItems;
$("selectVisible").onclick=()=>{const filter=$("configFilter").value;configItems.filter(item=>filter==="all"||item.state===filter).forEach(item=>selectedIds.add(item.id));renderConfigItems()};
$("clearSelection").onclick=()=>{selectedIds.clear();renderConfigItems()};
$("export").onclick=async()=>{const status=$("exportStatus");status.textContent="Generating and validating…";$("exportBody").textContent="";$("download").hidden=true;try{const q=new URLSearchParams({format:$("format").value});if($("userId").value.trim())q.set("userId",$("userId").value.trim());if($("subscriptionId").value.trim())q.set("subscriptionId",$("subscriptionId").value.trim());if($("format").value!=="subscription"){const selected=Array.from(selectedIds).filter(id=>configItems.some(item=>item.id===id));const filter=$("configFilter").value;const visible=configItems.filter(item=>filter==="all"||item.state===filter).map(item=>item.id);const ids=selected.length?selected:visible;if(ids.length)q.set("ids",ids.join(","));}const r=await api("/internal/config-studio?"+q.toString());lastExport=r.value;status.textContent="Validated "+r.value.count+" export item(s). Excluded: "+JSON.stringify(r.value.excluded);$("exportBody").textContent=r.value.body;$("download").hidden=false}catch(e){status.textContent="Export failed: "+String(e)}};
$("download").onclick=()=>{if(!lastExport)return;const blob=new Blob([lastExport.body],{type:lastExport.contentType});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=lastExport.filename;a.click();URL.revokeObjectURL(url)};
$("pulse").onclick=async()=>{show("pulseResult",{status:"running"});try{const r=await api("/internal/pulse");show("pulseResult",r.value)}catch(e){show("pulseResult",{status:"failed_or_unavailable",error:String(e)})}};
$("speed").onclick=async()=>{show("speedResult",{status:"running"});const started=performance.now();try{const r=await api("/internal/speed",{method:"POST",body:"{}"});show("speedResult",{...r.value,clientObservedApiRoundTripMs:Math.max(0,performance.now()-started),clientTimingScope:"browser-observed request/response total; distinct from server-side operation durations"})}catch(e){show("speedResult",{status:"failed_or_unavailable",error:String(e),clientObservedApiRoundTripMs:Math.max(0,performance.now()-started)})}};
$("routes").onclick=async()=>{show("routeResult",{status:"running"});try{const r=await api("/internal/route-advisor");show("routeResult",r.value)}catch(e){show("routeResult",{status:"failed_or_unavailable",error:String(e)})}};
loadConfigs();
</script></body></html>`;
  return new Response(html, { headers: { "content-type": "text/html; charset=UTF-8", "cache-control": "no-store" } });
}
