-- Member credential storage and one-time invitation lifecycle.
-- Passwords are never stored in plaintext; password_hash is a versioned
-- PBKDF2-SHA-256 encoded value generated by the application.
ALTER TABLE users ADD COLUMN password_hash TEXT;

CREATE TABLE member_invites (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  token_hash TEXT NOT NULL UNIQUE,
  created_by TEXT NOT NULL,
  created_at TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  consumed_at TEXT,
  revoked_at TEXT,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE INDEX idx_member_invites_user_id ON member_invites(user_id);
CREATE INDEX idx_member_invites_expires_at ON member_invites(expires_at);
